name: Build & Publish Integration Registry

on:
  push:
    paths:
      - 'integrations/**'
      - 'scripts/build-registry.ts'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Yarn v4
        run: |
          corepack enable
          yarn set version stable
      - name: Install dependencies
        run: yarn install

      - name: Build registry.yaml
        run: yarn tsx scripts/build-registry.ts

      - name: Commit registry.yaml if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add registry.yaml
          git diff --staged --quiet || git commit -m "Update registry.yaml"
          git push origin main

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Prepare pages directory
        run: |
          mkdir -p dist-pages
          cp -r integrations dist-pages/
          cp registry.yaml dist-pages/

      - name: Upload registry.yaml to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-pages'

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-pages
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
