name: Build & Publish Integration Registry

on:
  push:
    paths:
      - 'integrations/**'
      - 'scripts/build-registry.ts'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build registry.json
        run: node scripts/build-registry.ts

      - name: Commit registry.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add registry.json
          git diff --staged --quiet || git commit -m "Update registry.json"
          git push origin main

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload registry.json to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
